Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/10/2020
Var
   num : inteiro



Inicio
   escreva("Digite um valor:")
   leia(num)

   se (num > 10) entao
      escreva("é maior que 10")
   senao
      escreva("é menor que 10")
   fimse



Fimalgoritmo